# Generated by Django 5.0.3 on 2024-03-29 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2500)),
                ('location', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('jobType', models.CharField(max_length=30)),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='category.category')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posted_job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['postedAt'],
            },
        ),
    ]
